---
#############################################################
# These settings specify plugin paths and names             #
#############################################################
plugin_settings:
  # Folders
  metric_plugin_folder      :   "./lib/"
  archive_reader_plugin_folder: "./lib/"
  archive_writer_plugin_folder: "./lib/"

  # Metrics to load at startup
  load_metrics: ["isotropic_Schwarzschild", "KerrSchild_Kerr"]
  
  # Archive readers to load at startup
  load_readers: ["zip"]
  
  # Ttrajectory writers to load at startup
  load_writers: ["ascii"]

############################################################
# These settings govern the behavior of the ARKODE         #
# integrator                                               #
############################################################
integrator_settings:
  # Error tolerances
  absolute_tolerance: 1.0e-12
  relative_tolerance: 1.0e-12

  # Specifies the maximum number of error test failures 
  # permitted in attempting one step, before returning with
  # an error.
  max_error_test_fails: 20

  # Specifies the maximum number of nonlinear solver
  # iterations permitted per RK stage within each time step.
  max_nonlinear_iterations: 8

  # Specifies the maximum number of steps to be taken by
  # the solver in its attempt to reach the next output time,
  # before ARKStep will return with an error.
  max_steps: 100000

  # Specifies the method to use for predicting implicit
  # solutions.
  predictor_method_order: 1

  # Specifies the safety factor used within the nonlinear 
  # solver convergence test.
  convergence_coefficient: 1.0e-7

############################################################
# These settings govern the behavior of "dump-metric"      #
############################################################
dump_metric_settings:
  # Extension of the dumped data
  extension: ".ascii"

  # Size of the domain: [-radius, radius] in all directions
  radius: 10
  
  # Number of points in each direction to compute
  points: 5